// PRODUCTS ACTIONS
export const SET_PRODUCTS = "SET_PRODUCTS"
export const SET_PRODUCTS_LOADING = 'SET_PRODUCTS_LOADING'
export const SORT_PRICE_UP = 'SORT_PRICE_UP'
export const SORT_PRICE_DOWN = 'SORT_PRICE_DOWN'
export const SORT_TIME_UP = 'SORT_TIME_UP'
export const SORT_TIME_DOWN = 'SORT_TIME_DOWN'

// CART ACTIONS
export const SET_CART = 'SET_CART'
export const CLOSE_CART = 'CLOSE_CART'
export const TOGGLE_CART = 'TOGGLE_CART'

// CATEGORIES ACTIONS
export const SET_CATEGORIES = 'SET_CATEGORIES' 

// BELT ACTIONS:
export const SET_BELT = 'SET_BELT'